// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal.proto

package com.nero.im.protobuf.proto;

public final class Internal {
  private Internal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InternalMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.nero.im.protobuf.proto.InternalMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *协议版本号。第一版本：1，以此类推。
     * </pre>
     *
     * <code>required int32 version = 1;</code>
     * @return Whether the version field is set.
     */
    boolean hasVersion();
    /**
     * <pre>
     *协议版本号。第一版本：1，以此类推。
     * </pre>
     *
     * <code>required int32 version = 1;</code>
     * @return The version.
     */
    int getVersion();

    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>required int64 id = 2;</code>
     * @return Whether the id field is set.
     */
    boolean hasId();
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>required int64 id = 2;</code>
     * @return The id.
     */
    long getId();

    /**
     * <pre>
     *发送模块
     * </pre>
     *
     * <code>required .com.nero.im.protobuf.proto.InternalMsg.Module from = 3;</code>
     * @return Whether the from field is set.
     */
    boolean hasFrom();
    /**
     * <pre>
     *发送模块
     * </pre>
     *
     * <code>required .com.nero.im.protobuf.proto.InternalMsg.Module from = 3;</code>
     * @return The from.
     */
    Internal.InternalMsg.Module getFrom();

    /**
     * <pre>
     *接收模块
     * </pre>
     *
     * <code>required .com.nero.im.protobuf.proto.InternalMsg.Module dest = 4;</code>
     * @return Whether the dest field is set.
     */
    boolean hasDest();
    /**
     * <pre>
     *接收模块
     * </pre>
     *
     * <code>required .com.nero.im.protobuf.proto.InternalMsg.Module dest = 4;</code>
     * @return The dest.
     */
    Internal.InternalMsg.Module getDest();

    /**
     * <pre>
     *发送时间
     * </pre>
     *
     * <code>required int64 createTime = 5;</code>
     * @return Whether the createTime field is set.
     */
    boolean hasCreateTime();
    /**
     * <pre>
     *发送时间
     * </pre>
     *
     * <code>required int64 createTime = 5;</code>
     * @return The createTime.
     */
    long getCreateTime();

    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>required .com.nero.im.protobuf.proto.InternalMsg.MsgType msgType = 6;</code>
     * @return Whether the msgType field is set.
     */
    boolean hasMsgType();
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>required .com.nero.im.protobuf.proto.InternalMsg.MsgType msgType = 6;</code>
     * @return The msgType.
     */
    Internal.InternalMsg.MsgType getMsgType();

    /**
     * <pre>
     *消息体
     * </pre>
     *
     * <code>optional string msgBody = 7;</code>
     * @return Whether the msgBody field is set.
     */
    boolean hasMsgBody();
    /**
     * <pre>
     *消息体
     * </pre>
     *
     * <code>optional string msgBody = 7;</code>
     * @return The msgBody.
     */
    String getMsgBody();
    /**
     * <pre>
     *消息体
     * </pre>
     *
     * <code>optional string msgBody = 7;</code>
     * @return The bytes for msgBody.
     */
    com.google.protobuf.ByteString
        getMsgBodyBytes();
  }
  /**
   * Protobuf type {@code com.nero.im.protobuf.proto.InternalMsg}
   */
  public static final class InternalMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.nero.im.protobuf.proto.InternalMsg)
      InternalMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use InternalMsg.newBuilder() to construct.
    private InternalMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InternalMsg() {
      from_ = 0;
      dest_ = 0;
      msgType_ = 0;
      msgBody_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new InternalMsg();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private InternalMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              version_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readInt64();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              Internal.InternalMsg.Module value = Internal.InternalMsg.Module.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                from_ = rawValue;
              }
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              Internal.InternalMsg.Module value = Internal.InternalMsg.Module.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                dest_ = rawValue;
              }
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              createTime_ = input.readInt64();
              break;
            }
            case 48: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              Internal.InternalMsg.MsgType value = Internal.InternalMsg.MsgType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(6, rawValue);
              } else {
                bitField0_ |= 0x00000020;
                msgType_ = rawValue;
              }
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              msgBody_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Internal.internal_static_com_nero_im_protobuf_proto_InternalMsg_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Internal.internal_static_com_nero_im_protobuf_proto_InternalMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Internal.InternalMsg.class, Internal.InternalMsg.Builder.class);
    }

    /**
     * Protobuf enum {@code com.nero.im.protobuf.proto.InternalMsg.Module}
     */
    public enum Module
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CONNECTOR = 0;</code>
       */
      CONNECTOR(0),
      /**
       * <code>TRANSFER = 1;</code>
       */
      TRANSFER(1),
      /**
       * <code>CLIENT = 2;</code>
       */
      CLIENT(2),
      ;

      /**
       * <code>CONNECTOR = 0;</code>
       */
      public static final int CONNECTOR_VALUE = 0;
      /**
       * <code>TRANSFER = 1;</code>
       */
      public static final int TRANSFER_VALUE = 1;
      /**
       * <code>CLIENT = 2;</code>
       */
      public static final int CLIENT_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static Module valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Module forNumber(int value) {
        switch (value) {
          case 0: return CONNECTOR;
          case 1: return TRANSFER;
          case 2: return CLIENT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Module>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Module> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Module>() {
              public Module findValueByNumber(int number) {
                return Module.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Internal.InternalMsg.getDescriptor().getEnumTypes().get(0);
      }

      private static final Module[] VALUES = values();

      public static Module valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Module(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.nero.im.protobuf.proto.InternalMsg.Module)
    }

    /**
     * Protobuf enum {@code com.nero.im.protobuf.proto.InternalMsg.MsgType}
     */
    public enum MsgType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>GREET = 0;</code>
       */
      GREET(0),
      /**
       * <code>ACK = 1;</code>
       */
      ACK(1),
      /**
       * <code>ERROR = 2;</code>
       */
      ERROR(2),
      ;

      /**
       * <code>GREET = 0;</code>
       */
      public static final int GREET_VALUE = 0;
      /**
       * <code>ACK = 1;</code>
       */
      public static final int ACK_VALUE = 1;
      /**
       * <code>ERROR = 2;</code>
       */
      public static final int ERROR_VALUE = 2;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static MsgType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static MsgType forNumber(int value) {
        switch (value) {
          case 0: return GREET;
          case 1: return ACK;
          case 2: return ERROR;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MsgType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
              public MsgType findValueByNumber(int number) {
                return MsgType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Internal.InternalMsg.getDescriptor().getEnumTypes().get(1);
      }

      private static final MsgType[] VALUES = values();

      public static MsgType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MsgType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.nero.im.protobuf.proto.InternalMsg.MsgType)
    }

    private int bitField0_;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <pre>
     *协议版本号。第一版本：1，以此类推。
     * </pre>
     *
     * <code>required int32 version = 1;</code>
     * @return Whether the version field is set.
     */
    @Override
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *协议版本号。第一版本：1，以此类推。
     * </pre>
     *
     * <code>required int32 version = 1;</code>
     * @return The version.
     */
    @Override
    public int getVersion() {
      return version_;
    }

    public static final int ID_FIELD_NUMBER = 2;
    private long id_;
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>required int64 id = 2;</code>
     * @return Whether the id field is set.
     */
    @Override
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>required int64 id = 2;</code>
     * @return The id.
     */
    @Override
    public long getId() {
      return id_;
    }

    public static final int FROM_FIELD_NUMBER = 3;
    private int from_;
    /**
     * <pre>
     *发送模块
     * </pre>
     *
     * <code>required .com.nero.im.protobuf.proto.InternalMsg.Module from = 3;</code>
     * @return Whether the from field is set.
     */
    @Override public boolean hasFrom() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     *发送模块
     * </pre>
     *
     * <code>required .com.nero.im.protobuf.proto.InternalMsg.Module from = 3;</code>
     * @return The from.
     */
    @Override public Internal.InternalMsg.Module getFrom() {
      @SuppressWarnings("deprecation")
      Internal.InternalMsg.Module result = Internal.InternalMsg.Module.valueOf(from_);
      return result == null ? Internal.InternalMsg.Module.CONNECTOR : result;
    }

    public static final int DEST_FIELD_NUMBER = 4;
    private int dest_;
    /**
     * <pre>
     *接收模块
     * </pre>
     *
     * <code>required .com.nero.im.protobuf.proto.InternalMsg.Module dest = 4;</code>
     * @return Whether the dest field is set.
     */
    @Override public boolean hasDest() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     *接收模块
     * </pre>
     *
     * <code>required .com.nero.im.protobuf.proto.InternalMsg.Module dest = 4;</code>
     * @return The dest.
     */
    @Override public Internal.InternalMsg.Module getDest() {
      @SuppressWarnings("deprecation")
      Internal.InternalMsg.Module result = Internal.InternalMsg.Module.valueOf(dest_);
      return result == null ? Internal.InternalMsg.Module.CONNECTOR : result;
    }

    public static final int CREATETIME_FIELD_NUMBER = 5;
    private long createTime_;
    /**
     * <pre>
     *发送时间
     * </pre>
     *
     * <code>required int64 createTime = 5;</code>
     * @return Whether the createTime field is set.
     */
    @Override
    public boolean hasCreateTime() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     *发送时间
     * </pre>
     *
     * <code>required int64 createTime = 5;</code>
     * @return The createTime.
     */
    @Override
    public long getCreateTime() {
      return createTime_;
    }

    public static final int MSGTYPE_FIELD_NUMBER = 6;
    private int msgType_;
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>required .com.nero.im.protobuf.proto.InternalMsg.MsgType msgType = 6;</code>
     * @return Whether the msgType field is set.
     */
    @Override public boolean hasMsgType() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>required .com.nero.im.protobuf.proto.InternalMsg.MsgType msgType = 6;</code>
     * @return The msgType.
     */
    @Override public Internal.InternalMsg.MsgType getMsgType() {
      @SuppressWarnings("deprecation")
      Internal.InternalMsg.MsgType result = Internal.InternalMsg.MsgType.valueOf(msgType_);
      return result == null ? Internal.InternalMsg.MsgType.GREET : result;
    }

    public static final int MSGBODY_FIELD_NUMBER = 7;
    private volatile Object msgBody_;
    /**
     * <pre>
     *消息体
     * </pre>
     *
     * <code>optional string msgBody = 7;</code>
     * @return Whether the msgBody field is set.
     */
    @Override
    public boolean hasMsgBody() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     *消息体
     * </pre>
     *
     * <code>optional string msgBody = 7;</code>
     * @return The msgBody.
     */
    @Override
    public String getMsgBody() {
      Object ref = msgBody_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msgBody_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *消息体
     * </pre>
     *
     * <code>optional string msgBody = 7;</code>
     * @return The bytes for msgBody.
     */
    @Override
    public com.google.protobuf.ByteString
        getMsgBodyBytes() {
      Object ref = msgBody_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msgBody_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFrom()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDest()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCreateTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsgType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt64(2, id_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeEnum(3, from_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeEnum(4, dest_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeInt64(5, createTime_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeEnum(6, msgType_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, msgBody_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, from_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, dest_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, createTime_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, msgType_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, msgBody_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Internal.InternalMsg)) {
        return super.equals(obj);
      }
      Internal.InternalMsg other = (Internal.InternalMsg) obj;

      if (hasVersion() != other.hasVersion()) return false;
      if (hasVersion()) {
        if (getVersion()
            != other.getVersion()) return false;
      }
      if (hasId() != other.hasId()) return false;
      if (hasId()) {
        if (getId()
            != other.getId()) return false;
      }
      if (hasFrom() != other.hasFrom()) return false;
      if (hasFrom()) {
        if (from_ != other.from_) return false;
      }
      if (hasDest() != other.hasDest()) return false;
      if (hasDest()) {
        if (dest_ != other.dest_) return false;
      }
      if (hasCreateTime() != other.hasCreateTime()) return false;
      if (hasCreateTime()) {
        if (getCreateTime()
            != other.getCreateTime()) return false;
      }
      if (hasMsgType() != other.hasMsgType()) return false;
      if (hasMsgType()) {
        if (msgType_ != other.msgType_) return false;
      }
      if (hasMsgBody() != other.hasMsgBody()) return false;
      if (hasMsgBody()) {
        if (!getMsgBody()
            .equals(other.getMsgBody())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasVersion()) {
        hash = (37 * hash) + VERSION_FIELD_NUMBER;
        hash = (53 * hash) + getVersion();
      }
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getId());
      }
      if (hasFrom()) {
        hash = (37 * hash) + FROM_FIELD_NUMBER;
        hash = (53 * hash) + from_;
      }
      if (hasDest()) {
        hash = (37 * hash) + DEST_FIELD_NUMBER;
        hash = (53 * hash) + dest_;
      }
      if (hasCreateTime()) {
        hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getCreateTime());
      }
      if (hasMsgType()) {
        hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
        hash = (53 * hash) + msgType_;
      }
      if (hasMsgBody()) {
        hash = (37 * hash) + MSGBODY_FIELD_NUMBER;
        hash = (53 * hash) + getMsgBody().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Internal.InternalMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Internal.InternalMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Internal.InternalMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Internal.InternalMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Internal.InternalMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Internal.InternalMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Internal.InternalMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Internal.InternalMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Internal.InternalMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Internal.InternalMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Internal.InternalMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Internal.InternalMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Internal.InternalMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.nero.im.protobuf.proto.InternalMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.nero.im.protobuf.proto.InternalMsg)
        Internal.InternalMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Internal.internal_static_com_nero_im_protobuf_proto_InternalMsg_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Internal.internal_static_com_nero_im_protobuf_proto_InternalMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Internal.InternalMsg.class, Internal.InternalMsg.Builder.class);
      }

      // Construct using com.nero.im.protobuf.proto.Internal.InternalMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        from_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        dest_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        createTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        msgType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        msgBody_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Internal.internal_static_com_nero_im_protobuf_proto_InternalMsg_descriptor;
      }

      @Override
      public Internal.InternalMsg getDefaultInstanceForType() {
        return Internal.InternalMsg.getDefaultInstance();
      }

      @Override
      public Internal.InternalMsg build() {
        Internal.InternalMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Internal.InternalMsg buildPartial() {
        Internal.InternalMsg result = new Internal.InternalMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.version_ = version_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.id_ = id_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.from_ = from_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.dest_ = dest_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.createTime_ = createTime_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          to_bitField0_ |= 0x00000020;
        }
        result.msgType_ = msgType_;
        if (((from_bitField0_ & 0x00000040) != 0)) {
          to_bitField0_ |= 0x00000040;
        }
        result.msgBody_ = msgBody_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Internal.InternalMsg) {
          return mergeFrom((Internal.InternalMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Internal.InternalMsg other) {
        if (other == Internal.InternalMsg.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasFrom()) {
          setFrom(other.getFrom());
        }
        if (other.hasDest()) {
          setDest(other.getDest());
        }
        if (other.hasCreateTime()) {
          setCreateTime(other.getCreateTime());
        }
        if (other.hasMsgType()) {
          setMsgType(other.getMsgType());
        }
        if (other.hasMsgBody()) {
          bitField0_ |= 0x00000040;
          msgBody_ = other.msgBody_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        if (!hasVersion()) {
          return false;
        }
        if (!hasId()) {
          return false;
        }
        if (!hasFrom()) {
          return false;
        }
        if (!hasDest()) {
          return false;
        }
        if (!hasCreateTime()) {
          return false;
        }
        if (!hasMsgType()) {
          return false;
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Internal.InternalMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Internal.InternalMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int version_ ;
      /**
       * <pre>
       *协议版本号。第一版本：1，以此类推。
       * </pre>
       *
       * <code>required int32 version = 1;</code>
       * @return Whether the version field is set.
       */
      @Override
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       *协议版本号。第一版本：1，以此类推。
       * </pre>
       *
       * <code>required int32 version = 1;</code>
       * @return The version.
       */
      @Override
      public int getVersion() {
        return version_;
      }
      /**
       * <pre>
       *协议版本号。第一版本：1，以此类推。
       * </pre>
       *
       * <code>required int32 version = 1;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *协议版本号。第一版本：1，以此类推。
       * </pre>
       *
       * <code>required int32 version = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0;
        onChanged();
        return this;
      }

      private long id_ ;
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>required int64 id = 2;</code>
       * @return Whether the id field is set.
       */
      @Override
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>required int64 id = 2;</code>
       * @return The id.
       */
      @Override
      public long getId() {
        return id_;
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>required int64 id = 2;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>required int64 id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0L;
        onChanged();
        return this;
      }

      private int from_ = 0;
      /**
       * <pre>
       *发送模块
       * </pre>
       *
       * <code>required .com.nero.im.protobuf.proto.InternalMsg.Module from = 3;</code>
       * @return Whether the from field is set.
       */
      @Override public boolean hasFrom() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       *发送模块
       * </pre>
       *
       * <code>required .com.nero.im.protobuf.proto.InternalMsg.Module from = 3;</code>
       * @return The from.
       */
      @Override
      public Internal.InternalMsg.Module getFrom() {
        @SuppressWarnings("deprecation")
        Internal.InternalMsg.Module result = Internal.InternalMsg.Module.valueOf(from_);
        return result == null ? Internal.InternalMsg.Module.CONNECTOR : result;
      }
      /**
       * <pre>
       *发送模块
       * </pre>
       *
       * <code>required .com.nero.im.protobuf.proto.InternalMsg.Module from = 3;</code>
       * @param value The from to set.
       * @return This builder for chaining.
       */
      public Builder setFrom(Internal.InternalMsg.Module value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        from_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送模块
       * </pre>
       *
       * <code>required .com.nero.im.protobuf.proto.InternalMsg.Module from = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFrom() {
        bitField0_ = (bitField0_ & ~0x00000004);
        from_ = 0;
        onChanged();
        return this;
      }

      private int dest_ = 0;
      /**
       * <pre>
       *接收模块
       * </pre>
       *
       * <code>required .com.nero.im.protobuf.proto.InternalMsg.Module dest = 4;</code>
       * @return Whether the dest field is set.
       */
      @Override public boolean hasDest() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       *接收模块
       * </pre>
       *
       * <code>required .com.nero.im.protobuf.proto.InternalMsg.Module dest = 4;</code>
       * @return The dest.
       */
      @Override
      public Internal.InternalMsg.Module getDest() {
        @SuppressWarnings("deprecation")
        Internal.InternalMsg.Module result = Internal.InternalMsg.Module.valueOf(dest_);
        return result == null ? Internal.InternalMsg.Module.CONNECTOR : result;
      }
      /**
       * <pre>
       *接收模块
       * </pre>
       *
       * <code>required .com.nero.im.protobuf.proto.InternalMsg.Module dest = 4;</code>
       * @param value The dest to set.
       * @return This builder for chaining.
       */
      public Builder setDest(Internal.InternalMsg.Module value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        dest_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收模块
       * </pre>
       *
       * <code>required .com.nero.im.protobuf.proto.InternalMsg.Module dest = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDest() {
        bitField0_ = (bitField0_ & ~0x00000008);
        dest_ = 0;
        onChanged();
        return this;
      }

      private long createTime_ ;
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>required int64 createTime = 5;</code>
       * @return Whether the createTime field is set.
       */
      @Override
      public boolean hasCreateTime() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>required int64 createTime = 5;</code>
       * @return The createTime.
       */
      @Override
      public long getCreateTime() {
        return createTime_;
      }
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>required int64 createTime = 5;</code>
       * @param value The createTime to set.
       * @return This builder for chaining.
       */
      public Builder setCreateTime(long value) {
        bitField0_ |= 0x00000010;
        createTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送时间
       * </pre>
       *
       * <code>required int64 createTime = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCreateTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        createTime_ = 0L;
        onChanged();
        return this;
      }

      private int msgType_ = 0;
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>required .com.nero.im.protobuf.proto.InternalMsg.MsgType msgType = 6;</code>
       * @return Whether the msgType field is set.
       */
      @Override public boolean hasMsgType() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>required .com.nero.im.protobuf.proto.InternalMsg.MsgType msgType = 6;</code>
       * @return The msgType.
       */
      @Override
      public Internal.InternalMsg.MsgType getMsgType() {
        @SuppressWarnings("deprecation")
        Internal.InternalMsg.MsgType result = Internal.InternalMsg.MsgType.valueOf(msgType_);
        return result == null ? Internal.InternalMsg.MsgType.GREET : result;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>required .com.nero.im.protobuf.proto.InternalMsg.MsgType msgType = 6;</code>
       * @param value The msgType to set.
       * @return This builder for chaining.
       */
      public Builder setMsgType(Internal.InternalMsg.MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000020;
        msgType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>required .com.nero.im.protobuf.proto.InternalMsg.MsgType msgType = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgType() {
        bitField0_ = (bitField0_ & ~0x00000020);
        msgType_ = 0;
        onChanged();
        return this;
      }

      private Object msgBody_ = "";
      /**
       * <pre>
       *消息体
       * </pre>
       *
       * <code>optional string msgBody = 7;</code>
       * @return Whether the msgBody field is set.
       */
      public boolean hasMsgBody() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <pre>
       *消息体
       * </pre>
       *
       * <code>optional string msgBody = 7;</code>
       * @return The msgBody.
       */
      public String getMsgBody() {
        Object ref = msgBody_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msgBody_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *消息体
       * </pre>
       *
       * <code>optional string msgBody = 7;</code>
       * @return The bytes for msgBody.
       */
      public com.google.protobuf.ByteString
          getMsgBodyBytes() {
        Object ref = msgBody_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          msgBody_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息体
       * </pre>
       *
       * <code>optional string msgBody = 7;</code>
       * @param value The msgBody to set.
       * @return This builder for chaining.
       */
      public Builder setMsgBody(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        msgBody_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息体
       * </pre>
       *
       * <code>optional string msgBody = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgBody() {
        bitField0_ = (bitField0_ & ~0x00000040);
        msgBody_ = getDefaultInstance().getMsgBody();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息体
       * </pre>
       *
       * <code>optional string msgBody = 7;</code>
       * @param value The bytes for msgBody to set.
       * @return This builder for chaining.
       */
      public Builder setMsgBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        msgBody_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.nero.im.protobuf.proto.InternalMsg)
    }

    // @@protoc_insertion_point(class_scope:com.nero.im.protobuf.proto.InternalMsg)
    private static final Internal.InternalMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Internal.InternalMsg();
    }

    public static Internal.InternalMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<InternalMsg>
        PARSER = new com.google.protobuf.AbstractParser<InternalMsg>() {
      @Override
      public InternalMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InternalMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InternalMsg> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<InternalMsg> getParserForType() {
      return PARSER;
    }

    @Override
    public Internal.InternalMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_nero_im_protobuf_proto_InternalMsg_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_nero_im_protobuf_proto_InternalMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016internal.proto\022\032com.nero.im.protobuf.p" +
      "roto\"\352\002\n\013InternalMsg\022\017\n\007version\030\001 \002(\005\022\n\n" +
      "\002id\030\002 \002(\003\022<\n\004from\030\003 \002(\0162..com.nero.im.pr" +
      "otobuf.proto.InternalMsg.Module\022<\n\004dest\030" +
      "\004 \002(\0162..com.nero.im.protobuf.proto.Inter" +
      "nalMsg.Module\022\022\n\ncreateTime\030\005 \002(\003\022@\n\007msg" +
      "Type\030\006 \002(\0162/.com.nero.im.protobuf.proto." +
      "InternalMsg.MsgType\022\017\n\007msgBody\030\007 \001(\t\"1\n\006" +
      "Module\022\r\n\tCONNECTOR\020\000\022\014\n\010TRANSFER\020\001\022\n\n\006C" +
      "LIENT\020\002\"(\n\007MsgType\022\t\n\005GREET\020\000\022\007\n\003ACK\020\001\022\t" +
      "\n\005ERROR\020\002B\nB\010Internal"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_nero_im_protobuf_proto_InternalMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_nero_im_protobuf_proto_InternalMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_nero_im_protobuf_proto_InternalMsg_descriptor,
        new String[] { "Version", "Id", "From", "Dest", "CreateTime", "MsgType", "MsgBody", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
